name: Run azd hooks
trigger: none

pool:
  vmImage: windows-latest

parameters:
  - name: subscriptionId
    displayName: subscription id
    type: string
  - name: location
    displayName: location
    type: string
    default: "eastus2"


jobs:
  - job: RunHooks
    steps:
      - task: PowerShell@2
        displayName: Install azd
        inputs:
          targetType: inline
          script: |

            # powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' -OutFile 'install-azd.ps1'"

            # powershell ./install-azd.ps1 -Version 'daily'
            winget install microsoft.azd


      # - task: Bash@3
      #   displayName: Install template
      #   inputs:
      #     targetType: inline
      #     script: |

      #       azd version

      #       azd config set auth.useAzCliAuth "true"
      #       azd config set defaults.subscription ${{ parameters.subscriptionId }}
      #       azd config set defaults.location ${{ parameters.location }}

      #       environmentName="sdk-azdhook-$(uuidgen | cut -c 1-6)"
      #       azd init -e $environmentName


      - task: AzureCLI@2
        displayName: Run azd hooks
        inputs:
          azureSubscription: tomServiceConnection1
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |

            azd version

            azd config set auth.useAzCliAuth "true"
            azd config set defaults.subscription ${{ parameters.subscriptionId }}
            azd config set defaults.location ${{ parameters.location }}

            environmentName="sdk-azdhook-$(uuidgen | cut -c 1-6)"
            azd init -e $environmentName

            chmod -R +x ./hooks/

            azd up --no-prompt

            azd down --purge --force

